// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Get the number of runs for Math.random 
		int numberOfRuns = Integer.parseInt(args[0]);
		int runCount = 0; 
		int greaterThenHalf = 0; 
		int lessThenHalf = 0;
		while (runCount < numberOfRuns) {
			double randomNumber = Math.random();
			if (randomNumber > 0.5) {
				greaterThenHalf = greaterThenHalf + 1;
			} else {
				lessThenHalf = lessThenHalf + 1;
			}
			runCount = runCount + 1;
		}
		System.out.println("> 0.5: " + greaterThenHalf + " times");
		System.out.println("<= 0.5: " + lessThenHalf + " times");
		if (lessThenHalf > 0){
			double ratio = (double) greaterThenHalf/ (double) lessThenHalf; 
			System.out.println("Ratio: " + ratio);
		}
	}
}
